# Generated by Django 3.1.4 on 2020-12-15 19:41

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=90)),
                ('main', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dummy', models.ImageField(default='default.png', upload_to='blogimages')),
                ('bg', models.ImageField(default='default.png', upload_to='blogimages')),
            ],
        ),
    ]
